version: "3.9"
services:
  gpioc-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/gpioc-debug:${TAG}
    ports:
      - 2230:2230
    devices:
      - "/dev/gpiochip0"

  gpioc:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/gpioc:${TAG}
    devices:
      - "/dev/gpiochip0"
