version: "2.4"
services:
  weston:
    environment:
      - ACCEPT_FSL_EULA=1
    container_name: weston
    image: torizon/weston-vivante:1
    # Required to get udev events from host udevd via netlink
    network_mode: host
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
      - type: bind
        source: /run/udev
        target: /run/udev
    # Add device access rights through cgroup...
    device_cgroup_rules:
      # ... for tty0
      - "c 4:0 rmw"
      # ... for tty7
      - "c 4:7 rmw"
      # ... for /dev/input devices
      - "c 13:* rmw"
      - "c 199:* rmw"
      # ... for /dev/dri devices
      - "c 226:* rmw"

  kiosk:
    container_name: kiosk
    # kiosk with wait-for-it
    # see ../Dockerfile.kiosk-wait
    image: torizonextras/arm64v8-kiosk-wait
    network_mode: host
    entrypoint: []
    # wait for the blazor application
    command:
      - wait-for-it
      - localhost:5000
      - -t
      - "120"
      - --
      - bash 
      - -c
      - sleep 30 && /usr/bin/start-browser http://localhost:5000
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /var/run/dbus
        target: /var/run/dbus
      - type: bind
        source: /dev/dri
        target: /dev/dri
    cap_add:
      - CAP_SYS_ADMIN
    depends_on:
      - weston 
    shm_size: "256mb"
    device_cgroup_rules:
      # ... for /dev/dri devices
      - "c 226:* rmw"
